name: IOTIS-P
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - joblib
  - pytest
  - pytorch
  - cpuonly
  - tqdm
  - seaborn
  - pip:
    - scipy
